# Use an official Node runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package*.json /app/

# Install any needed packages
RUN npm install

# Copy the rest of the application code into the container
COPY . /app

# Build the React app for production
RUN npm run build

# Expose port 3000 for the React app
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
