# Use an official Python runtime as the base image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app

# Expose port 5000 to the host so you can access it
EXPOSE 5000

# Define environment variable for Flask
ENV FLASK_APP=run.py

# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
